### ISSUE TITLE
Readme error?

### ISSUE THREAD

**Issue by KaMiila** [orangeturtle739/panther#1]
In your readme under Installation, don't you mean layman -a panther?  lizard does not exist in the layman repository list.  What is lizard?  Even your .xml states panther.

**Comment by orangeturtle739** [comment]
:upside_down_face: 

I'll fix that...

Lizard is a completely different (and unrelated thing): https://github.com/cornell-brg/lizard

**Comment by orangeturtle739** [comment]
Resolved by 91945c3c0439768d85cba3b10cd7d9be594617cc.
