### ISSUE TITLE
ckb-next bump 0.4.3

### ISSUE THREAD

**Issue by gtlt** [orangeturtle739/panther#3]
Hi, I used this ebuild  but not an expert !
```
EAPI=5

inherit cmake-utils linux-info

DESCRIPTION="RGB Driver for Linux and macOS"
HOMEPAGE="https://github.com/ckb-next/ckb-next"
SRC_URI="https://github.com/ckb-next/ckb-next/archive/v$PV.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-libs/quazip
	dev-qt/qtcore:5
	dev-qt/qtgui:5
	dev-qt/qtnetwork:5
	dev-qt/qtwidgets:5
	x11-misc/xcb
	dev-libs/libdbusmenu-qt
	dev-qt/linguist-tools
	dev-python/PyQt5[x11extras]
	dev-qt/qt-docs[x11extras]
	!!app-misc/ckb"
RDEPEND="${DEPEND}"

DOCS=( README.md )

CONFIG_CHECK="INPUT_UINPUT"


src_configure() {
	local mycmakeargs=(-DDISABLE_UPDATER=1)
	cmake-utils_src_configure
}
```

**Comment by orangeturtle739** [comment]
I would expect it to look just like the [0.4.2 ebuild](https://github.com/orangeturtle739/panther/blob/master/app-misc/ckb-next/ckb-next-0.4.2.ebuild). Are those extra dependencies needed?

**Comment by gtlt** [comment]
I didn't tried without them but are reported in the ckb-next [release notes](https://github.com/ckb-next/ckb-next/releases/tag/v0.4.3)...
_The following new dependencies have been introduced: Qt5 X11Extras, xcb, xcb-screensaver, xcb-ewmh, Qt5 translation tools, dbusmenu-qt5_
I think xcb at least should be added. I don't know the impact for x11extras and translation

**Comment by orangeturtle739** [comment]
Ok! I'm happy to accept a pull request if you have one, otherwise I will try update this soon.
